#!/usr/bin/env bash

git switch main
git pull origin main

version=`node -p "require('./package.json').version"`
echo "version: $version"

git tag -a "v$version" -m "v$version"
git push origin "v$version"

npm publish